texto_sumar = Sumar
texto_restar = Restar
texto_multiplicar = Multiplicar
texto_dividir = Dividir
texto_cambiar_idioma = Cambiar idioma
texto_salir = Salir
titulo = Calculadora
mensaje_error = Error: División por cero
mensaje_operacion = Elige una operación:
mensaje_ingresar_numero1 = Ingresa el primer número:
mensaje_ingresar_numero2 = Ingresa el segundo número:
mensaje_cambiar_idioma = ¿cúal idioma quieres?
lblRes = El resultado es: 
ingles = Ingles
espanol = Español
frances = Frances
